import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Nav from './components/nav'
import Image1 from '../public/home-page.jpg'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>The Exhibitionist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Nav/>
        <div className="h-screen">
        <div className="flex flex-col mt-2">
            <h1 className="text-center text-2xl">Discover the world through art</h1>
            <p className="text-center my-2 text-xl">Find your next destination at our gallery guide</p>
            <div className="">
                <Image className="m-auto" src={Image1} style={{width: "500px"}}></Image>
            </div>
            <div className='text-center my-4'>
            <Link href="/explore" >
              <p className=" px-3 py-2 border-2 border-black m-auto" style={{width: "100px"}}>Explore</p>
              </Link>
            </div>
          </div>
        </div>
    </>
  )
}
